import Sidebar from "@/components/sidebar";
import { faMagnifyingGlass, faMicrophone, faVideo } from "@fortawesome/free-solid-svg-icons";
import {faBell} from '@fortawesome/free-regular-svg-icons'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import fireship from '../assets/images/fireship.jpg'
import beast from '../assets/images/beast.webp'
import thumb from '../assets/images/thumb.jpeg'
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Slider from "react-slick";
import verified from "../assets/images/verified.png"
import SuggestedLinks from "@/components/suggestedLinks";
import Cards from "@/components/cards";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {

  const settings = {
    dots: false,
    infinite: false,
    speed: 400,
    variableWidth: true,
    slidesToShow: 9,
    slidesToScroll: 1
  };

  const count = 10;
  const API_KEY = "AIzaSyC0H1tbrJnleqt5zDbcnPz_QmdlirL37TU";
  const q = "funny";
  const url = `https://www.googleapis.com/youtube/v3/search?key=${API_KEY}&maxResults=${count}&part=snippet&type=video&q=${q}`;
  const [YTvideos, setYTVideos] = useState(null);

  useEffect(() => {

    // axios.get(url)
    // .then(response => {
    //   console.log(response);
    // })

  });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <main>
          <div className="youtube-main-wrapper">
            <Sidebar />
            <div className="video-wrapper">
              <div className="search-bar">
                <div className="search-input">
                  <FontAwesomeIcon icon={faMagnifyingGlass} />
                  <input type="text" placeholder="Looking for something?" />
                  <Link href="#">
                    <span>
                      <FontAwesomeIcon icon={faMicrophone} />
                    </span>
                  </Link>
                </div>
                <div className="search-shortcuts">
                  <Link href="#">
                    <FontAwesomeIcon icon={faVideo} />
                  </Link>
                  <Link href="#">
                    <svg
                      height="24"
                      viewBox="0 0 24 24"
                      width="24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill="#d2d3d5"
                        d="M4 11h6a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1zm10 0h6a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1h-6a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1zM4 21h6a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1zm10 0h6a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1h-6a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1z"
                      />
                    </svg>{" "}
                  </Link>
                  <Link href="#" className="notifications">
                    <FontAwesomeIcon icon={faBell} />
                  </Link>
                  <Link href="#" className="profile-image">
                    <Image alt="fireship" src={fireship} />
                  </Link>
                </div>
              </div>

              <div className="suggested-categories">
                  <Slider {...settings}>
                    <SuggestedLinks text={"All"} isActive={true} />
                    <SuggestedLinks text={"Unity"} isActive={false} />
                    <SuggestedLinks text={"Blenders"} isActive={false} />
                    <SuggestedLinks text={"Dota 2"} isActive={false} />
                    <SuggestedLinks text={"Editing"} isActive={false} />
                    <SuggestedLinks text={"Computer Program"} isActive={false} />
                    <SuggestedLinks text={"Apple Macbook Pro"} isActive={false} />
                    <SuggestedLinks text={"Unreal Engine"} isActive={false} />
                    <SuggestedLinks text={"Editing"} isActive={false} />
                    <SuggestedLinks text={"Editing"} isActive={false} />
                    <SuggestedLinks text={"Computer Program"} isActive={false} />
                    <SuggestedLinks text={"Apple Macbook Pro"} isActive={false} />
                    <SuggestedLinks text={"Unreal Engine"} isActive={false} />
                    <SuggestedLinks text={"Editing"} isActive={false} />
                  </Slider>
                </div>

                <div className="video-cards-flex">

                  <Cards channelName={"Mr Beast"} channelLogo={beast} isChannelVerfied={true} Videothumbnail={thumb} Videotitle={"Video title mr beast title mr beast Video title mr beast title mr beast Video title"} Videoviews={"555K"} Videodate={"1 year ago"} />
                  <Cards channelName={"Youtube"} channelLogo={beast} isChannelVerfied={false} Videothumbnail={thumb} Videotitle={"YOutube Famous Video"} Videoviews={"10.1M"} Videodate={"3 year ago"} />

                </div>
            </div>
          </div>
        </main>
      </>
    </>
  );
}
