import Sidebar from "@/components/sidebar";
import Head from "next/head";
import Image from "next/image";
import { Col, Row } from "react-bootstrap";
import Dropdown from "react-bootstrap/Dropdown";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <main>
            <div className="youtube-main-wrapper">

              <Sidebar />              
              <div className="video-wrapper">
                
              </div>

            </div>
        </main>
      </>
      
    </>
  );
}
