import Sidebar from "@/components/sidebar";
import { faMagnifyingGlass, faMicrophone, faVideo } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <main>
            <div className="youtube-main-wrapper">

              <Sidebar />              
              <div className="video-wrapper">
                <div className="search-bar">
                  <div className="search-input">
                    <FontAwesomeIcon icon={faMagnifyingGlass}/>
                    <input type="text" placeholder="Looking for something?"/>
                    <Link href='javascript:void(0)'><span><FontAwesomeIcon icon={faMicrophone}/></span></Link>
                  </div>
                  <div className="search-shortcuts">
                    <Link href="javascript:void(0)"><FontAwesomeIcon icon={faVideo} /></Link>
                    <Link href="javascript:void(0)"><FontAwesomeIcon icon={faVideo} /></Link>
                    <Link href="javascript:void(0)"><FontAwesomeIcon icon={faVideo} /></Link>
                    <Link href="javascript:void(0)"><FontAwesomeIcon icon={faVideo} /></Link>
                  </div>
                </div>
              </div>

            </div>
        </main>
      </>
      
    </>
  );
}
